#!/bin/bash





echo -n enter password:
read -s PASSWORD

cd `dirname $0` && cd ..

VERSION_CODE=`cat build.gradle  | grep versionCode | sed -e 's/^.*: //g'`



./gradlew :demo:assembleRelease -Pandroid.injected.signing.store.file=/home/dan/workspace/android/keystore.jks \
  -Pandroid.injected.signing.store.password="$PASSWORD" \
  -Pandroid.injected.signing.key.alias=jmopidy \
  -Pandroid.injected.signing.key.password="$PASSWORD" || exit 1




cp app/build/outputs/apk/release/demo-release.apk releases/jmopidy_v${VERSION_CODE}.apk
